---
name: Chart Linting

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      charts:
        description: List of Changed Charts
        required: true
        type: string
      artifactory_helm_repo_name:
        description: Helm repo mnemonic name, as referred in ct.yaml
        type: string
        default: csm-algol60
      artifactory_hostname:
        description: Docker registry name to pre-auhtenticate to pull chart images
        type: string
        default: artifactory.algol60.net
      helm_version:
        description: 'Version of Helm to Intall'
        required: false
        type: string
        default: 'v3.11.3'
    secrets:
      artifactory_username:
        description: Username for Helm repository and Docker registry
        required: true
      artifactory_password:
        description: Password for Helm repository and Docker registry
        required: true
jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix: ${{ fromJSON(inputs.charts) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ inputs.helm_version }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Lint
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            branch="${GITHUB_BASE_REF}"
          else
            branch="${{ github.event.repository.default_branch }}"
          fi
          ct lint --target-branch ${branch#refs/heads/} \
          --lint-conf .github/lintconf.yaml --chart-yaml-schema .github/chart_schema.yaml \
          --helm-repo-extra-args "${{ inputs.artifactory_helm_repo_name }}=--username ${{ secrets.artifactory_username }} --password ${{ secrets.artifactory_password }}"
